### ISSUE TITLE
Full Text Search fails to install

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1501]
I have no clue about what's causing this. Do you have an idea @Ark74 @daita ?

```
Installing fulltextsearch...
fulltextsearch already enabled
Installing fulltextsearch_elasticsearch...
fulltextsearch_elasticsearch already enabled
Installing files_fulltextsearch...
files_fulltextsearch already enabled
{
    "search_platform": "OCA\\FullTextSearch_ElasticSearch\\Platform\\ElasticSearchPlatform",
    "app_navigation": "0",
    "provider_indexed": "",
    "cron_err_reset": "0",
    "tick_ttl": "1800"
}
{
    "elastic_host": "http:\/\/zrnzoeotsrguxznhcopajyqbfc:uDBPpPX1Bar1cGdNEYpBBECJ0T@localhost:9200",
    "elastic_index": "zrnzoeotsrguxznhcopajyqbfc-index",
    "fields_limit": "10000",
    "es_ver_below66": "0",
    "analyzer_tokenizer": "standard"
}
{
    "files_local": "1",
    "files_external": "0",
    "files_group_folders": "0",
    "files_encrypted": "0",
    "files_federated": "0",
    "files_size": "20",
    "files_pdf": "1",
    "files_office": "1",
    "files_image": "0",
    "files_audio": "0"
}
An unhandled exception has been thrown:
Error: Wrong parameters for Elasticsearch\Common\Exceptions\ServerErrorResponseException([string $message [, long $code [, Throwable $previous = NULL]]]) in /var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:665
Stack trace:
#0 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(665): Exception->__construct()
#1 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(320): Elasticsearch\Connections\Connection->process5xxError()
#2 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#3 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then()
#4 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/ezimuel/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then()
#5 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(329): GuzzleHttp\Ring\Core::proxy()
#6 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(227): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#7 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(105): Elasticsearch\Connections\Connection->performRequest()
#8 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/BooleanRequestWrapper.php(38): Elasticsearch\Transport->performRequest()
#9 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(969): Elasticsearch\Namespaces\BooleanRequestWrapper::performRequest()
#10 /var/www/nextcloud/apps/fulltextsearch_elasticsearch/lib/Platform/ElasticSearchPlatform.php(176): Elasticsearch\Client->ping()
#11 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Index.php(380): OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform->testPlatform()
#12 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Index.php(257): OCA\FullTextSearch\Command\Index->testPlatform()
#13 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Index->execute()
#14 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run()
#15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1012): OC\Core\Command\Base->run()
#16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand()
#17 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#18 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#19 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#20 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#21 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:index failed
```

The strange thing is that after this I did an Uninstall (option in the script), and then a new installation. That worked. 

Did the same thing again, and this error popped up (again). :thinking:

**Comment by enoch85** [comment]
@szaimen If you want to investigate?

**Comment by enoch85** [comment]
Tested again, it usually works the second time.

All good.
