### ISSUE TITLE
Automatic update to 23.0.1 broke nextcloud

### ISSUE THREAD

**Issue by benkuly** [nextcloud/vm#2205]
### Steps To Reproduce

Start nextcloud update manually via menu.sh

### Expected Result

no error

### Actual Result

```
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <user_ldap> ...
An unhandled exception has been thrown:
Error: Call to undefined method OC\DB\QueryBuilder\QueryBuilder::executeQuery() in /var/www/nextcloud/apps/user_ldap/lib/Migration/GroupMappingMigration.php:56
Stack trace:
#0 /var/www/nextcloud/apps/user_ldap/lib/Migration/Version1130Date20220110154717.php(54): OCA\User_LDAP\Migration\GroupMappingMigration->copyGroupMappingData()
#1 /var/www/nextcloud/lib/private/DB/MigrationService.php(528): OCA\User_LDAP\Migration\Version1130Date20220110154717->preSchemaChange()
#2 /var/www/nextcloud/lib/private/DB/MigrationService.php(426): OC\DB\MigrationService->executeStep()
#3 /var/www/nextcloud/lib/private/legacy/OC_App.php(1012): OC\DB\MigrationService->migrate()
#4 /var/www/nextcloud/lib/private/Updater.php(347): OC_App::updateApp()
#5 /var/www/nextcloud/lib/private/Updater.php(262): OC\Updater->doAppUpgrade()
#6 /var/www/nextcloud/lib/private/Updater.php(134): OC\Updater->doUpgrade()
#7 /var/www/nextcloud/core/Command/Upgrade.php(249): OC\Updater->upgrade()
#8 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#13 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#14 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#15 {main}
```

### Build Version

the major version before 23.0.1

### Environment

By using the scripts

### Environment Details

- Ubuntu

**Comment by enoch85** [comment]
Hi, just for some context, disable ldap and run the update again.

**Comment by benkuly** [comment]
It was also my fault: I tried to upgrade from 21 to 23. Disabling ldap, upgrade from 21 to 22 to 23 and then activate ldap worked.

**Comment by enoch85** [comment]
Glad you sorted it! :)
