### ISSUE TITLE
Weather Status Fails after Update

### ISSUE THREAD

**Issue by stxdigitizing** [nextcloud/vm#2236]
### Steps To Reproduce

Login Dashboard Weather Status not working get following error after update.

```
[weather_status] Warning: https://api.opentopodata.org/v1/srtm30mAPI error : GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.opentopodata.org/v1/srtm30m?locations=29.6115203%2C-95.5368283 in /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
Stack trace:
#0 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection()
#1 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError()
#2 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish()
#3 /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php(113): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): OC\Http\Client\DnsPinMiddleware->OC\Http\Client\{closure}()
#5 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#6 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#7 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke()
#8 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#9 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke()
#10 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer()
#11 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync()
#12 /var/www/nextcloud/lib/private/Http/Client/Client.php(223): GuzzleHttp\Client->request()
#13 /var/www/nextcloud/apps/weather_status/lib/Service/WeatherStatusService.php(415): OC\Http\Client\Client->get()
#14 /var/www/nextcloud/apps/weather_status/lib/Service/WeatherStatusService.php(232): OCA\WeatherStatus\Service\WeatherStatusService->requestJSON()
#15 /var/www/nextcloud/apps/weather_status/lib/Service/WeatherStatusService.php(189): OCA\WeatherStatus\Service\WeatherStatusService->getAltitude()
#16 /var/www/nextcloud/apps/weather_status/lib/Controller/WeatherStatusController.php(94): OCA\WeatherStatus\Service\WeatherStatusService->setLocation()
#17 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(217): OCA\WeatherStatus\Controller\WeatherStatusController->setLocation()
#18 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(126): OC\AppFramework\Http\Dispatcher->executeController()
#19 /var/www/nextcloud/lib/private/AppFramework/App.php(157): OC\AppFramework\Http\Dispatcher->dispatch()
#20 /var/www/nextcloud/lib/private/Route/Router.php(302): OC\AppFramework\App::main()
#21 /var/www/nextcloud/ocs/v1.php(62): OC\Route\Router->match()
#22 /var/www/nextcloud/ocs/v2.php(23): require_once('/var/www/nextcl...')
#23 {main}


```

### Expected Result

Display current Weather 

### Actual Result

Stuck on Loading Weather...

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/56180085/154416384-8cbccdec-2d66-4711-a66e-d200964f2cc7.png)

### Build Version

Nextcloud HanssonIT VM (23.0.2)

### Environment

By downloading the VM

### Environment Details

Purchased [Nextcloud HanssonIT VM]

**Comment by enoch85** [comment]
Did the same update, no issue here. Maybe your internet connection is laggy?

We do not recommend using QNAP since it's proven to be very unstable over the years.

**Comment by stxdigitizing** [comment]
Wouldn't think so. I have a business network. I let it sit for about 5 to 6 minutes and it finally came thru. Maybe it's just temporary.

**Comment by enoch85** [comment]
Yes, that might be the issue, I actually don't know. Just a random error output doesn't tell me much. :/

**Comment by stxdigitizing** [comment]
I'll check my logs and report back.

**Comment by stxdigitizing** [comment]
Yes I was right, It was a temporary issue. The problem is no longer presetnt.
