### ISSUE TITLE
Unable to update to NC 12: ERROR 1045 (28000): Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by gnul** [nextcloud/vm#238]
## Steps to reproduce
1. sudo bash /var/scripts/update.sh

## Expected behaviour
Update NC  succesfully

## Actual behaviour
```
...
Latest release is: 12.0.0. Current version is: 11.0.3.
New version available? Upgrade continues...
Backing up files and upgrading to Nextcloud 12.0.0 in 10 seconds...
ress CTRL+C to abort.
Backing up data...

Backup OK?
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Doing mysqldump of all databases...
Enter password:
mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: YES) when trying to connect
```

## Server configuration

NC 11.0.3 (stable)
VM 11-0-3
fresh install

## Network
DHCP
Ports 443 & 80 open 

#### Log file (/var/ncdata/nextcloud.log)
```
{"reqId":"iw\/9ejp2aOahzycpITik","remoteAddr":"213.243.128.113","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 409 Parent node does not exist\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Conflict\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('InstantUpload\\\/C...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1143,\"User\":\"ncadmin\"}","level":4,"time":"2017-05-14T17:19:03+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/InstantUpload\/Camera\/","user":"ncadmin","version":"11.0.3.2"}
{"reqId":"ePA41kcCC2ACy1XvNSUM","remoteAddr":"46.166.138.183","app":"index","message":"Exception: {\"Exception\":\"RedisException\",\"Message\":\"Redis server went away\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Memcache\\\/Redis.php(52): Redis->get('ae43a0f73ea4481...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/App\\\/InfoParser.php(54): OC\\\\Memcache\\\\Redis->get('\\\/var\\\/www\\\/nextcl...')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(714): OC\\\\App\\\\InfoParser->parse('\\\/var\\\/www\\\/nextcl...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(62): OC_App::getAppInfo('files')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(196): OC\\\\AppFramework\\\\App::buildAppNamespace('files')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(117): OC_App::registerAutoloading('files', '\\\/var\\\/www\\\/nextcl...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(676): OC_App::loadApps(Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1092): OC::init()\\n#8 \\\/var\\\/www\\\/nextcloud\\\/index.php(38): require_once('\\\/var\\\/www\\\/nextcl...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Memcache\\\/Redis.php\",\"Line\":52}","level":3,"time":"2017-05-14T17:36:29+00:00","method":"GET","url":"\/apps\/serverinfo\/update","user":"--","version":"11.0.3.2"}
{"reqId":"ePA41kcCC2ACy1XvNSUM","remoteAddr":"46.166.138.183","app":"core","message":"Exception: {\"Exception\":\"RedisException\",\"Message\":\"Redis server went away\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Memcache\\\/Redis.php(52): Redis->get('ae43a0f73ea4481...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/App\\\/InfoParser.php(54): OC\\\\Memcache\\\\Redis->get('\\\/var\\\/www\\\/nextcl...')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(714): OC\\\\App\\\\InfoParser->parse('\\\/var\\\/www\\\/nextcl...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(62): OC_App::getAppInfo('files')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(196): OC\\\\AppFramework\\\\App::buildAppNamespace('files')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(117): OC_App::registerAutoloading('files', '\\\/var\\\/www\\\/nextcl...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(676): OC_App::loadApps(Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1092): OC::init()\\n#8 \\\/var\\\/www\\\/nextcloud\\\/index.php(38): require_once('\\\/var\\\/www\\\/nextcl...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Memcache\\\/Redis.php\",\"Line\":52}","level":3,"time":"2017-05-14T17:36:29+00:00","method":"GET","url":"\/apps\/serverinfo\/update","user":"--","version":"11.0.3.2"}
{"reqId":"ePA41kcCC2ACy1XvNSUM","remoteAddr":"46.166.138.183","app":"core","message":"Exception: {\"Exception\":\"RedisException\",\"Message\":\"Redis server went away\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Memcache\\\/Redis.php(52): Redis->get('ae43a0f73ea4481...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(147): OC\\\\Memcache\\\\Redis->get('-favicon.ico')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template\\\/functions.php(170): OC\\\\URLGenerator->imagePath('', 'favicon.ico')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(13): image_path('', 'favicon.ico')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(174): include('\\\/var\\\/www\\\/nextcl...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(149): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/nextcl...', NULL)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(229): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(251): OC_Template->fetchPage()\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(130): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(364): OC\\\\Template\\\\Base->printPage()\\n#10 \\\/var\\\/www\\\/nextcloud\\\/index.php(59): OC_Template::printExceptionErrorPage(Object(RedisException))\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Memcache\\\/Redis.php\",\"Line\":52}","level":3,"time":"2017-05-14T17:36:29+00:00","method":"GET","url":"\/apps\/serverinfo\/update","user":"--","version":"11.0.3.2"}
{"reqId":"ePA41kcCC2ACy1XvNSUM","remoteAddr":"46.166.138.183","app":"PHP","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/RedisFactory.php#61","level":3,"time":"2017-05-14T17:36:29+00:00","method":"GET","url":"\/apps\/serverinfo\/update","user":"--","version":"11.0.3.2"}
{"reqId":"enIS4SJbuXT9h\/7g0jzr","remoteAddr":"46.166.138.183","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php:806\nStack trace:\n#0 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(2018): OC\\Files\\Filesystem::normalizePath('\/ncadmin\/files\/...')\n#1 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(1156): OC\\Files\\View->unlockFile('\/Documents\/Next...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/nextcloud\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php#806","level":3,"time":"2017-05-14T18:10:58+00:00","method":"GET","url":"\/apps\/serverinfo\/update","user":"ncadmin","version":"11.0.3.2"}
{"reqId":"iUVpa3BX1veNK28QkIxY","remoteAddr":"5.153.233.11","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php:806\nStack trace:\n#0 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(2018): OC\\Files\\Filesystem::normalizePath('\/ncadmin\/files\/...')\n#1 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(1156): OC\\Files\\View->unlockFile('\/Documents\/Next...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/nextcloud\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php#806","level":3,"time":"2017-05-14T18:20:25+00:00","method":"POST","url":"\/heartbeat","user":"--","version":"11.0.3.2"}
{"reqId":"v6ULLd78swvwXjaiy8+L","remoteAddr":"46.166.138.183","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php:806\nStack trace:\n#0 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(2018): OC\\Files\\Filesystem::normalizePath('\/ncadmin\/files\/...')\n#1 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(1156): OC\\Files\\View->unlockFile('\/Documents\/Next...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/nextcloud\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php#806","level":3,"time":"2017-05-14T18:24:36+00:00","method":"GET","url":"\/apps\/serverinfo\/update","user":"ncadmin","version":"11.0.3.2"}
{"reqId":"HUQ4UZSKUc\/Ue3Djl3ty","remoteAddr":"46.166.138.183","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php:806\nStack trace:\n#0 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(2018): OC\\Files\\Filesystem::normalizePath('\/ncadmin\/files\/...')\n#1 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(1156): OC\\Files\\View->unlockFile('\/Documents\/Next...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/nextcloud\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php#806","level":3,"time":"2017-05-14T18:45:07+00:00","method":"GET","url":"\/apps\/serverinfo\/update","user":"ncadmin","version":"11.0.3.2"}
{"reqId":"ND1N\/59WwDmKFORyce9f","remoteAddr":"46.166.138.183","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php:806\nStack trace:\n#0 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(2018): OC\\Files\\Filesystem::normalizePath('\/ncadmin\/files\/...')\n#1 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(1156): OC\\Files\\View->unlockFile('\/Documents\/Next...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/nextcloud\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php#806","level":3,"time":"2017-05-14T18:51:25+00:00","method":"GET","url":"\/apps\/serverinfo\/update","user":"ncadmin","version":"11.0.3.2"}
{"reqId":"Vq3oSpA0BELdVjCQcuYu","remoteAddr":"188.238.229.164","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 1024000 got 757760\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(104): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #14)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #14)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1072): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('20160618_223229...', Resource id #14)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('InstantUpload\\\/C...', Resource id #14, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":405,\"User\":\"ncadmin\"}","level":4,"time":"2017-05-14T21:13:40+00:00","method":"PUT","url":"\/remote.php\/webdav\/InstantUpload\/Camera\/20160618_223229_HDR~01.jpg-chunking-1252693798-4-1","user":"ncadmin","version":"11.0.3.2"}
{"reqId":"XWmYvJwjt41gA723FtRN","remoteAddr":"139.162.116.133","app":"core","message":"Trusted domain error. \"139.162.116.133\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-15T01:33:11+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"Z2fhrqCiZGpRv6c+NyFv","remoteAddr":"74.82.47.2","app":"core","message":"Trusted domain error. \"74.82.47.2\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-15T13:05:01+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"xfq86kLc2RtzBnNsXyjf","remoteAddr":"163.172.68.183","app":"core","message":"Trusted domain error. \"163.172.68.183\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-15T16:51:55+00:00","method":"GET","url":"\/a2billing\/common\/javascript\/misc.js","user":"--","version":"11.0.3.2"}
{"reqId":"0ZZbOIgPHMg1UKb3gMz7","remoteAddr":"139.162.106.181","app":"core","message":"Trusted domain error. \"139.162.106.181\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-15T21:06:56+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"j2UThl+HxzgrUznJRx3B","remoteAddr":"163.172.68.183","app":"core","message":"Trusted domain error. \"163.172.68.183\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-16T17:34:45+00:00","method":"GET","url":"\/a2billing\/common\/javascript\/misc.js","user":"--","version":"11.0.3.2"}
{"reqId":"6HIgvvQ9IUc+4JEYPb5L","remoteAddr":"71.6.202.204","app":"core","message":"Trusted domain error. \"71.6.202.204\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-16T22:43:02+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"XQy61Sz6tufPz3Ixr5Hh","remoteAddr":"139.162.78.135","app":"core","message":"Trusted domain error. \"139.162.78.135\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-17T01:49:18+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"GEq5x2ZVqxDouWuMqaVn","remoteAddr":"74.82.47.4","app":"core","message":"Trusted domain error. \"74.82.47.4\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-17T10:59:48+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"eYkJQaHLx\/PuyfnMeoxX","remoteAddr":"107.170.205.167","app":"core","message":"Trusted domain error. \"107.170.205.167\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-17T20:46:02+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"ysFQg70CC3hgCOfNrQxs","remoteAddr":"107.170.205.167","app":"core","message":"Trusted domain error. \"107.170.205.167\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-17T20:46:03+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"o\/vjhlYFLoP4whZI2kQS","remoteAddr":"107.170.205.167","app":"core","message":"Trusted domain error. \"107.170.205.167\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-17T20:46:05+00:00","method":"GET","url":"\/core\/js\/oc.js?v=867ecb77ab77e88050e6c195d78053bd","user":"--","version":"11.0.3.2"}
{"reqId":"S1u48b0cqCXkcYZ\/Po4V","remoteAddr":"107.170.205.167","app":"core","message":"Trusted domain error. \"107.170.205.167\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-17T20:46:42+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"LC\/lBiyfR29C7GYVa0Xc","remoteAddr":"107.170.205.167","app":"core","message":"Trusted domain error. \"107.170.205.167\" tried to access using \"pilvessa.eu.\" as host.","level":2,"time":"2017-05-17T20:48:18+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"oocX5ljpQIkPbOrgRHa1","remoteAddr":"107.170.205.167","app":"core","message":"Trusted domain error. \"107.170.205.167\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-17T20:48:18+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"8dquH\/2GdDmsRkbsRdVQ","remoteAddr":"107.170.205.167","app":"core","message":"Trusted domain error. \"107.170.205.167\" tried to access using \"pilvessa.eu.\" as host.","level":2,"time":"2017-05-17T20:48:20+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"NDjgMvjGk0+EyV+QAojG","remoteAddr":"107.170.205.167","app":"core","message":"Trusted domain error. \"107.170.205.167\" tried to access using \"pilvessa.eu.\" as host.","level":2,"time":"2017-05-17T20:48:21+00:00","method":"GET","url":"\/core\/js\/oc.js?v=867ecb77ab77e88050e6c195d78053bd","user":"--","version":"11.0.3.2"}
{"reqId":"Ph96cvZPcFmAFKDCFnt4","remoteAddr":"71.6.202.204","app":"core","message":"Trusted domain error. \"71.6.202.204\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-18T08:04:00+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"1vUrSVxIDc\/K0oqfU8Jn","remoteAddr":"139.162.78.135","app":"core","message":"Trusted domain error. \"139.162.78.135\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-18T08:23:20+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"Xq+gl5Vr5\/7G+jn0RJS4","remoteAddr":"71.6.202.204","app":"core","message":"Trusted domain error. \"71.6.202.204\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-19T04:14:42+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"UK6IiQ+O54qPtbuZxETc","remoteAddr":"62.210.188.53","app":"core","message":"Trusted domain error. \"62.210.188.53\" tried to access using \"213.243.128.113:443\" as host.","level":2,"time":"2017-05-19T06:11:31+00:00","method":"GET","url":"\/\/","user":"--","version":"11.0.3.2"}
{"reqId":"ql+7\/o1yBlJfziDVjUZY","remoteAddr":"137.116.71.170","app":"core","message":"Trusted domain error. \"137.116.71.170\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-19T08:37:47+00:00","method":"GET","url":"\/robots.txt","user":"--","version":"11.0.3.2"}
{"reqId":"hW3ODJDRMvCs2tqrTDUx","remoteAddr":"139.162.113.204","app":"core","message":"Trusted domain error. \"139.162.113.204\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-19T12:44:27+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"yj0SIEPz9QgCW5RvhLhZ","remoteAddr":"71.6.202.204","app":"core","message":"Trusted domain error. \"71.6.202.204\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-20T00:20:55+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"ufG6YKMsl6vCkuNTXa0l","remoteAddr":"139.162.106.181","app":"core","message":"Trusted domain error. \"139.162.106.181\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-20T08:07:56+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"43VxAzAmhL5LyVg13sym","remoteAddr":"5.188.10.102","app":"core","message":"Trusted domain error. \"5.188.10.102\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-21T13:59:11+00:00","method":"HEAD","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"+0pnIcRSurLxkM\/PtnGi","remoteAddr":"139.162.116.133","app":"core","message":"Trusted domain error. \"139.162.116.133\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-22T00:43:33+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"0CSapyCHEx3c\/TUhGhve","remoteAddr":"52.53.196.93","app":"core","message":"Trusted domain error. \"52.53.196.93\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-23T01:16:50+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"xsrxtOUlITrKhNrL8\/\/z","remoteAddr":"192.194.176.138","app":"core","message":"Login failed: 'ncadmin' (Remote IP: '192.194.176.138')","level":2,"time":"2017-05-23T11:15:53+00:00","method":"POST","url":"\/login","user":"--","version":"11.0.3.2"}
{"reqId":"3giUOs7Nt4txSvl\/tPpi","remoteAddr":"74.82.47.4","app":"core","message":"Trusted domain error. \"74.82.47.4\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-23T13:29:34+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"rInB42B06fJhyWAvEZgF","remoteAddr":"139.162.78.135","app":"core","message":"Trusted domain error. \"139.162.78.135\" tried to access using \"213.243.128.113\" as host.","level":2,"time":"2017-05-23T14:14:04+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
{"reqId":"xfGvuxQ19chU7tu9NkOg","remoteAddr":"106.75.96.96","app":"core","message":"Trusted domain error. \"106.75.96.96\" tried to access using \"213.243.128.113:443\" as host.","level":2,"time":"2017-05-23T18:08:05+00:00","method":"GET","url":"\/","user":"--","version":"11.0.3.2"}
```

**Comment by enoch85** [comment]
@gnul Thanks for reporting! 

When did you try to do this update? I recently changed the behaviur of the MySQL backup. 

Can you please run nextcloud_update.sh with debug mode set to `1` and post the output via hastebin or similar?

**Comment by enoch85** [comment]
I just tested to upgrade from 11.0.3 with the script and it worked.

**Comment by enoch85** [comment]
@gnul Any update?

**Comment by gnul** [comment]
Sorry for the delay.
I ran it few times the same day before I posted this issue.
[Here](https://hastebin.com/aseqatufav.bash) is the output of the nextcloud_update.sh

**Comment by enoch85** [comment]
@gnul Please run sudo bash -x /var/scripts/update.sh and post the output.

**Comment by gnul** [comment]
[Output](https://hastebin.com/oyikizatoc.diff) of sudo bash -x /var/scripts/update.sh

**Comment by enoch85** [comment]
@gnul Ok, what does this look like:cat /root/.my.cnf && cat /var/mysql_password.txt

**Comment by gnul** [comment]
[client]
password=''
cat: /var/mysql_password.txt: No such file or directory

**Comment by enoch85** [comment]
Ok, sorry to say but your MySQL password is gone. 

Test if this works: https://www.howtoforge.com/reset-forgotten-mysql-root-password

Then put your new password in .my.cnf and run the update again.
