### ISSUE TITLE
restore-backup.sh fails when running borg list

### ISSUE THREAD

**Issue by pq2** [nextcloud/vm#2427]
### Steps To Reproduce

1. Run restore-backup.sh
2. Get to the step where you have to enter the passphrase that was used to encrypt the borg backup
3. Enter the correct passphrase

### Expected Result

The backup is restored

### Actual Result

I get the following exception:
```
Failed to create/acquire the lock /tmp/backupdrive/.snapshots/@20230117_153551/borgbackup/NcVM/lock.exclusive ([Errno 30] Read-only file system: '/tmp/backupdrive/.snapshots/@20230117_153551/borgbackup/NcVM/lock.exclusive.h7_ncijc.tmp').
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5089, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5020, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 200, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 431, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait).acquire()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 387, in acquire
    with self._lock:
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 115, in __enter__
    return self.acquire()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 137, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /tmp/backupdrive/.snapshots/@20230117_153551/borgbackup/NcVM/lock.exclusive ([Errno 30] Read-only file system: '/tmp/backupdrive/.snapshots/@20230117_153551/borgbackup/NcVM/lock.exclusive.h7_ncijc.tmp').
```
Seems like write permissions for the drive are missing.

### Build Version

25.0.2.3

### Environment

By using the scripts

### Environment Details

- Ubuntu 22.04
- Intel Quad Core
- 8 GB RAM

```
Platform: Linux nextcloud 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64
Linux: Unknown Linux  
Borg: 1.2.0  Python: CPython 3.10.6 msgpack: 1.0.3 fuse: pyfuse3 3.2.0 [pyfuse3,llfuse]
PID: 4602  CWD: /home/ncadmin
sys.argv: ['/usr/bin/borg', 'list', '/tmp/backupdrive/.snapshots/@20230117_153551/borgbackup/NcVM']
SSH_ORIGINAL_COMMAND: None
```

**Comment by szaimen** [comment]
Yes, you need to choose a different directory. The snapshots dir is read only. Can you maybe show a acreenshot which directories get shown to you?

**Comment by szaimen** [comment]
fix here: https://github.com/nextcloud/vm/pull/2428

**Comment by pq2** [comment]
Ah, thanks. That was my fault. It worked now.

**Comment by pq2** [comment]
> No, actually is this a UX problem. I've provided a fix in https://github.com/nextcloud/vm/pull/2428

I agree 😃. Thanks for the fix.
