### ISSUE TITLE
collabora errors, cannot get it to work after purchasing 1TB Nextcloud VM

### ISSUE THREAD

**Issue by eced77** [nextcloud/vm#405]
## Steps to reproduce
1. VM installation was good, no errors, however I cannot get collabora to work, both domains have SSL activated. 
2. when I click on test.odt document what it shows on nextcloud theme is 'Internal Server Error, The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.

Technical details

    Remote Address: x.x.x.x . => my gateway address
    Request ID: jYOhAVRcmESWDTbAoaUL

3. from /var/log/apache2/error.log I see the following:
[Wed Oct 25 18:00:35.139853 2017] [proxy_http:error] [pid 1712] (103)Software caused connection abort: [client 127.0.0.1:60024] AH01102: error reading status line from remote server 127.0.0.1:9980
[Wed Oct 25 18:00:35.139930 2017] [proxy:error] [pid 1712] [client 127.0.0.1:60024] AH00898: Error reading from remote server returned by /hosting/discovery
[Wed Oct 25 18:03:28.140386 2017] [proxy_http:error] [pid 2823] (103)Software caused connection abort: [client 127.0.0.1:60030] AH01102: error reading status line from remote server 127.0.0.1:9980
[Wed Oct 25 18:03:28.140437 2017] [proxy:error] [pid 2823] [client 127.0.0.1:60030] AH00898: Error reading from remote server returned by /hosting/discovery

## Expected behaviour
should be able to edit document

## Actual behaviour
produces internal server error

## Server configuration

**Server version:** (see your admin page) 12.0.3

**VM version** (master / released version)

**Updated from an older installed version or fresh install:** fresh install

## Network
**Do you use DHCP?** no, public static IP

**Is port 80 and/or 443 open?** yes

#### Log file (/var/ncdata/nextcloud.log)
```{"reqId":"zNSrClNAlvDQifBvo0S4","level":3,"time":"2017-10-25T18:17:17-04:00","remoteAddr":"192.168.1.254","user":"ncadmin","app":"richdocuments","method":"GET","url":"\/apps\/richdocuments\/index?fileId=147861&requesttoken=u3EG1wKg5lSc3N5DfwTk1D7nnnTxGaXx3VYDPsW7oLs%3D%3A3T5WuEHJ1B7RsI8iVEqj41S%2ByR%2BGe9LFmh43da7cys8%3D","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ServerException\",\"Message\":\"Server error response [url] https:\\\/\\\/office.minubeprivada.com\\\/hosting\\\/discovery [status code] 502 [reason phrase] Proxy Error\",\"Code\":502,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Subscriber\\\/HttpError.php(32): GuzzleHttp\\\\Exception\\\\RequestException::create(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Message\\\\Response))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Event\\\/Emitter.php(108): GuzzleHttp\\\\Subscriber\\\\HttpError->onComplete(Object(GuzzleHttp\\\\Event\\\\CompleteEvent), 'complete')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(91): GuzzleHttp\\\\Event\\\\Emitter->emit('complete', Object(GuzzleHttp\\\\Event\\\\CompleteEvent))\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#9 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(138): GuzzleHttp\\\\Client->get('https:\\\/\\\/office....', Array)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/richdocuments\\\/lib\\\/WOPI\\\/DiscoveryManager.php(84): OC\\\\Http\\\\Client\\\\Client->get('https:\\\/\\\/office....')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/richdocuments\\\/lib\\\/WOPI\\\/Parser.php(41): OCA\\\\Richdocuments\\\\WOPI\\\\DiscoveryManager->get()\\n#13 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/richdocuments\\\/lib\\\/TokenManager.php(117): OCA\\\\Richdocuments\\\\WOPI\\\\Parser->getUrlSrc('application\\\/vnd...')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/richdocuments\\\/lib\\\/Controller\\\/DocumentController.php(168): OCA\\\\Richdocuments\\\\TokenManager->getToken(*** sensitive parameters replaced ***)\\n#15 [internal function]: OCA\\\\Richdocuments\\\\Controller\\\\DocumentController->index('147861')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Richdocuments\\\\Controller\\\\DocumentController), 'index')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Richdocuments\\\\Controller\\\\DocumentController), 'index')\\n#19 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Richdocumen...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#20 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#21 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#22 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/richdocum...')\\n#23 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":89}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```cat /etc/hosts
127.0.0.1       localhost
127.0.1.1       eced.minubeprivada.com eced
127.0.0.1       office.minubeprivada.com office

docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
9272e4a30528        collabora/code      "/bin/sh -c 'bash ..."   22 hours ago        Up 46 seconds       127.0.0.1:9980->9980/tcp   keen_nightingale

netstat -lnpt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9980          0.0.0.0:*               LISTEN      10995/docker-proxy
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1616/mysqld
tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN      2184/perl
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      1627/spreed-webrtc-
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1226/sshd
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      5451/0
tcp6       0      0 127.0.0.1:7983          :::*                    LISTEN      2075/java
tcp6       0      0 :::80                   :::*                    LISTEN      1618/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      1226/sshd
tcp6       0      0 127.0.0.1:8983          :::*                    LISTEN      2075/java
tcp6       0      0 ::1:6010                :::*                    LISTEN      5451/0
tcp6       0      0 :::443                  :::*                    LISTEN      1618/apache2    

3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:80:51:98:07 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:80ff:fe51:9807/64 scope link
       valid_lft forever preferred_lft forever
95: veth10332a9@if94: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default
    link/ether f2:7f:e6:69:c0:52 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::f07f:e6ff:fe69:c052/64 scope link
       valid_lft forever preferred_lft forever

 /etc/apache2/sites-available/
root@eced:/etc/apache2/sites-available# ls -ltr
total 32
-rw-r--r-- 1 root root 6338 Apr  5  2016 default-ssl.conf
-rw-r--r-- 1 root root  617 Sep 24 06:59 nextcloud_http_domain_self_signed.conf
-rw-r--r-- 1 root root  870 Sep 24 06:59 nextcloud_ssl_domain_self_signed.conf
-rw-r--r-- 1 root root 1327 Oct 18 17:02 000-default.conf
-rw-r--r-- 1 root root 1805 Oct 18 17:21 minubeprivada.com.conf
-rw-r--r-- 1 root root 2889 Oct 22 00:26 office.minubeprivada.com.conf
-rw-r--r-- 1 root root 1845 Oct 24 20:38 eced.minubeprivada.com.conf
#### Screenshoots
<!--
Please use http://imgur.com/ for screenshots. Thanks!
-->

**Comment by enoch85** [comment]
How is this installed? Do you host it on a VPS somewhere or on your on server? Do you use a NGINX Reverse Proxy or similar? 

Most often it's a firewall / configuration issue on your end.

**Comment by eced77** [comment]
Is the 1TB VM I purchased from tech&me. I do not host, using vmware fusion on Macbook Pro. I follow instructions on your site, all I did is assigned it a static public IP, but it does the same if I use local private IP.
I do not use Nginx Reverse Proxy. Are there any other configurations I need to make besides just importing the ova template I purchased through your site?

**Comment by enoch85** [comment]
In order for everything to work you must open ports and such so that it's available to your server. The ports in question are 80 and 443. Are you running the Netowrk for the VM in bridged mode?

It works here, so there must be something that you do wrong on the configuration.

**Comment by enoch85** [comment]
Testing your adresses don't work. Are the VM turned off?

**Comment by enoch85** [comment]
Also, checking if the ports are open results in that the are closed. 

Please follow the instructions and try again. 

Thanks!

**Comment by eced77** [comment]
The VM is currently turned off, I’m going to re-install VM when I get back

**Comment by enoch85** [comment]
Just tested here on a fresh Digitalocean installation: https://cloud.techandme.se/s/7JGp3I9YGFOH5Gh

It works.

**Comment by eced77** [comment]
I re-installed and it worked fine, Thanks!!
