### ISSUE TITLE
Nextcloud - Installing fulltext search (elasticsearch)

### ISSUE THREAD

**Issue by reinhardhack** [nextcloud/vm#819]
## Steps to reproduce
1. 
2.
3.

## Expected behaviour
installing elasticsearch fulltextsearch vie script: 

## Actual behaviour
Error: In Index.php line 380: 
failed platform test.

## Server configuration

**Nextcloud server version: 15.0.7

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
Ready to use Image from "https://shop.hanssonit.se/"
## Network
10.10.10.15

**Is port 80 and/or 443 open?**
no, we have internal use only.
#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
@reinhardhack Most probably this is an issue in the app code.

cc @Ark74 @daita

**Comment by enoch85** [comment]
Related: https://github.com/nextcloud/fulltextsearch/issues/483

**Comment by daita** [comment]
Would not really defined this as an issue with the app code. It is just saying that Nextcloud could not reach Elasticsearch. Can be a lot of thing; like _Is elasticsearch running ?_

**Comment by reinhardhack** [comment]
After starting the service its up for a short time and then offline again

[cid:image001.png@01D4F39D.3D6A51E0]



Mit freundlichen Grüßen
Reinhard Hack
Netzwerktechnik


NETsystems - Business Computer & Service GmbH
Premstätter Straße 165
A-8054 Seiersberg-Pirka

Tel:  +43 316 23 12 00

www.netsystems.at<http://www.netsystems.at/>
office@netsystems.at<mailto:office@netsystems.at>

Firmenbuchnummer: FN 329930 t
Firmenbuchgericht: Landesger. F. ZRS Graz

Von: Maxence Lange <notifications@github.com>
Gesendet: Montag, 15. April 2019 14:30
An: nextcloud/vm <vm@noreply.github.com>
Cc: Reinhard Hack <r.hack@netsystems.at>; Mention <mention@noreply.github.com>
Betreff: Re: [nextcloud/vm] Nextcloud - Installing fulltext search (elasticsearch) (#819)


Would not really defined this as an issue with the app code. It is just saying that Nextcloud could not reach Elasticsearch. Can be a lot of thing; like Is elasticsearch running ?

**Comment by daita** [comment]
You will need to check elasticsearch logs and see why it stops

**Comment by reinhardhack** [comment]
Maybe Java Version?

[2019-04-15T15:20:21,500][INFO ][o.e.e.NodeEnvironment    ] [mJGkb97] using [1] data paths, mounts [[/ (/dev/mapper/nextcloud--vg-root)]], net usable_space [29.5gb], net total_space [38.1gb], types [ext4]
[2019-04-15T15:20:21,503][INFO ][o.e.e.NodeEnvironment    ] [mJGkb97] heap size [1007.3mb], compressed ordinary object pointers [true]
[2019-04-15T15:20:21,514][INFO ][o.e.n.Node               ] [mJGkb97] node name derived from node ID [mJGkb97ORL60VWrxYapzJQ]; set [node.name] to override
[2019-04-15T15:20:21,514][INFO ][o.e.n.Node               ] [mJGkb97] version[6.7.1], pid[46591], build[default/deb/2f32220/2019-04-02T15:59:27.961366Z], OS[Linux/4.15.0-47-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/10.0.2/10.0.2+13-Ubuntu-1ubuntu0.18.04.4]
[2019-04-15T15:20:21,514][INFO ][o.e.n.Node               ] [mJGkb97] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna$
[2019-04-15T15:20:24,144][ERROR][o.e.b.Bootstrap          ] [mJGkb97] Exception
java.lang.IllegalArgumentException: Plugin [ingest-attachment] was built for Elasticsearch version 6.6.2 but version 6.7.1 is running
        at org.elasticsearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:346) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:531) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:471) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:163) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.node.Node.<init>(Node.java:339) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.7.1.jar:6.7.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) [elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.7.1.jar:6.7.1]
[2019-04-15T15:20:24,150][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [mJGkb97] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Plugin [ingest-attachment] was built for Elasticsearch version 6.6.2 but version 6.7.1 is running
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.7.1.jar:6.7.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.7.1.jar:6.7.1]
Caused by: java.lang.IllegalArgumentException: Plugin [ingest-attachment] was built for Elasticsearch version 6.6.2 but version 6.7.1 is running
        at org.elasticsearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:346) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:531) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:471) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:163) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.node.Node.<init>(Node.java:339) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.7.1.jar:6.7.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.7.1.jar:6.7.1]



Mit freundlichen Grüßen
Reinhard Hack
Netzwerktechnik


NETsystems - Business Computer & Service GmbH
Premstätter Straße 165
A-8054 Seiersberg-Pirka

Tel:  +43 316 23 12 00

www.netsystems.at<http://www.netsystems.at/>
office@netsystems.at<mailto:office@netsystems.at>

Firmenbuchnummer: FN 329930 t
Firmenbuchgericht: Landesger. F. ZRS Graz

Von: Maxence Lange <notifications@github.com>
Gesendet: Montag, 15. April 2019 15:11
An: nextcloud/vm <vm@noreply.github.com>
Cc: Reinhard Hack <r.hack@netsystems.at>; Mention <mention@noreply.github.com>
Betreff: Re: [nextcloud/vm] Nextcloud - Installing fulltext search (elasticsearch) (#819)


You will need to check elasticsearch logs and see why it stops

**Comment by daita** [comment]
[2019-04-15T15:20:24,150][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [mJGkb97] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Plugin [ingest-attachment] was built for Elasticsearch version 6.6.2 but version 6.7.1 is running 

You need to remove the plugin ingest-attachment and reinstall it.

@enoch85: your script your do that to maintain the plugins at the same version

**Comment by Ark74** [comment]
Hmm, that's weird.
I maintain updates for the docker image ran on the VM scripts for fulltextsearch in nc.

And the latest build,
```
docker image inspect ark74/nc_fts:latest
[
    {
        "Id": "sha256:8a53f16c0c87a71482b10a374a6da83bab5e055afff6391578e214dd9734993f",
        "RepoTags": [
            "ark74/nc_fts:1.17.4_es6.7.0",
            "ark74/nc_fts:latest"
        ],
...
```
Have the following plugin versions,
```
GhmYeIs ingest-attachment 6.7.0
GhmYeIs readonlyrest      1.17.4
```
@reinhardhack you might wanna update to the latest docker version and test again.
That might solve your issue.

Cheers!

**Comment by enoch85** [comment]
@daita Sorry for my assumption.

> your script your do that to maintain the plugins at the same version

@Ark74 maintains the install script and the docker for FTS as mentioned above --^

**Comment by Ark74** [comment]
Seems that @reinhardhack has his own fts docker image, or what ever version shipped on the VM.
I don't see it as a bug.

**Comment by enoch85** [comment]
@reinhardhack can you confirm that this is **not** the FTS provided in the scripted install in the VM?

**Comment by enoch85** [comment]
This is not FTS, just tested to install it for a customer, and it worked.

**Comment by Ark74** [comment]
@reinhardhack fyi, [ES 6.7.1](https://hub.docker.com/r/ark74/nc_fts/tags/) have been released you can run it with the [update script](https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh).

Cheers!

**Comment by reinhardhack** [comment]
Thank you very much, ill try this.

But i think since i purged elasticsearch from my nextcloud it meight be broken…

But just paisting the link in my nextcloud doesnt work…

What am i doing wrong?

sudo: https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh: command not found



Mit freundlichen Grüßen
Reinhard Hack
Netzwerktechnik


NETsystems - Business Computer & Service GmbH
Premstätter Straße 165
A-8054 Seiersberg-Pirka

Tel:  +43 316 23 12 00

www.netsystems.at<http://www.netsystems.at/>
office@netsystems.at<mailto:office@netsystems.at>

Firmenbuchnummer: FN 329930 t
Firmenbuchgericht: Landesger. F. ZRS Graz

Von: Luis Guzman <notifications@github.com>
Gesendet: Montag, 22. April 2019 21:24
An: nextcloud/vm <vm@noreply.github.com>
Cc: Reinhard Hack <r.hack@netsystems.at>; Mention <mention@noreply.github.com>
Betreff: Re: [nextcloud/vm] Nextcloud - Installing fulltext search (elasticsearch) (#819)


@reinhardhack<https://github.com/reinhardhack> fyi, ES 6.7.1<https://hub.docker.com/r/ark74/nc_fts/tags/> have been released you can run it with the update script<https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh>.

Cheers!

**Comment by enoch85** [comment]
@reinhardhack Please ask in the forums: https://help.nextcloud.com

The command for running the update script is: `sudo bash /var/scripts/update.sh`
